/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sankalp
 */
public class A_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form A_dashboard
     */
    public A_dashboard() {
        initComponents();
        welcomearea.setText("Welcome Sir");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        showpatientbutton = new javax.swing.JButton();
        welcomearea = new javax.swing.JTextField();
        showbutton = new javax.swing.JButton();
        logoutbutton = new javax.swing.JButton();
        removebutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "s_id", "Name", "Designation", "Contact"
            }
        ));
        jScrollPane2.setViewportView(table);

        showpatientbutton.setText("Show Staff:-");
        showpatientbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpatientbuttonActionPerformed(evt);
            }
        });

        showbutton.setText("Show");
        showbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbuttonActionPerformed(evt);
            }
        });

        logoutbutton.setText("Logout");
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });

        removebutton.setText("Remove Selected Staff");
        removebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(showpatientbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removebutton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(156, 156, 156))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(welcomearea, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(logoutbutton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(welcomearea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(showpatientbutton)))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showbutton)
                    .addComponent(removebutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(logoutbutton)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showpatientbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpatientbuttonActionPerformed
        try {
            // TODO add your handling code here:
            DefaultTableModel tablemodel = (DefaultTableModel) table.getModel();
            deleteAllRows(tablemodel);
            Class.forName("com.mysql.jdbc.Driver");

            Statement mystmt=null;
            ResultSet myrs;
            int count=0;
            Connection myconn=null;
            String dburl="jdbc:mysql://localhost:3306/Hospital";
            String user="sankalp";
            String pass="qwerty";

            myconn=DriverManager.getConnection(dburl,user,pass);

            mystmt=myconn.createStatement();

            myrs=mystmt.executeQuery("select * from staff;");
            while(myrs.next()){
                int ID=myrs.getInt("s_id");
                String name=myrs.getString("s_name");
                String designation=myrs.getString("designation");
                long number= myrs.getLong("ph_no");
                System.out.println(ID +"->" + name +"->" + designation +"->" + number);
                tablemodel.addRow(new Object[]{ID,name,designation,number});
            }
            mystmt.close();
            myconn.close();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(dr_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_showpatientbuttonActionPerformed

    private void showbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbuttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tablemodel = (DefaultTableModel) table.getModel();
        int selectedrowindex = table.getSelectedRow();
        String pname= (String) tablemodel.getValueAt(selectedrowindex,1);
        System.out.print(pname);
        close();
        dr_dashboard P = new dr_dashboard(pname);
        P.setVisible(true);

    }//GEN-LAST:event_showbuttonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        // TODO add your handling code here:
        close();
        login L =new login();
        L.setVisible(true);
    }//GEN-LAST:event_logoutbuttonActionPerformed

    private void removebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removebuttonActionPerformed
        try {
            // TODO add your handling code here:
            
            DefaultTableModel tablemodel = (DefaultTableModel) table.getModel();
            int selectedrow = table.getSelectedRow();
            String s_id=tablemodel.getValueAt(selectedrow,0).toString();
            int sid=Integer.parseInt(s_id);
            
            Class.forName("com.mysql.jdbc.Driver");
            
            Statement mystmt=null;
            ResultSet myrs;
            int count=0;
            Connection myconn=null;
            String dburl="jdbc:mysql://localhost:3306/Hospital";
            String user="sankalp";
            String pass="qwerty";

            myconn=DriverManager.getConnection(dburl,user,pass);

            mystmt=myconn.createStatement();

            count=mystmt.executeUpdate("delete from staff where s_id ='"+sid+"';");
            JOptionPane.showMessageDialog(null,"Please Enter Correct Entries");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(A_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(A_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_removebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton removebutton;
    private javax.swing.JButton showbutton;
    private javax.swing.JButton showpatientbutton;
    private javax.swing.JTable table;
    private javax.swing.JTextField welcomearea;
    // End of variables declaration//GEN-END:variables

private void close(){
    WindowEvent winClosing=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
}
public static void deleteAllRows(final DefaultTableModel model) {
    for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
        model.removeRow(i);
    }
}

}
