/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import static hospital.login1.deleteAllRows;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sankalp
 */
public class dr_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dr_dashboard
     */
    public dr_dashboard() {
        initComponents();
    }
    String doctor_name;
    public dr_dashboard(String doctor) {
        initComponents();
        this.doctor_name=doctor;
        welcomearea.setText("Welcome " + doctor);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        showpatientbutton = new javax.swing.JButton();
        welcomearea = new javax.swing.JTextField();
        showbutton = new javax.swing.JButton();
        logoutbutton = new javax.swing.JButton();
        treatmentbutton = new javax.swing.JButton();
        dischargebutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "P-ID", "First Name", "Disease", "Dr_id"
            }
        ));
        jScrollPane2.setViewportView(table);

        showpatientbutton.setText("Show Patient's:-");
        showpatientbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpatientbuttonActionPerformed(evt);
            }
        });

        showbutton.setText("Show");
        showbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbuttonActionPerformed(evt);
            }
        });

        logoutbutton.setText("Logout");
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });

        treatmentbutton.setText("Go to treatment Section");
        treatmentbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treatmentbuttonActionPerformed(evt);
            }
        });

        dischargebutton.setText("Discharge Selected Patient");
        dischargebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dischargebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showpatientbutton)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(logoutbutton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(showbutton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dischargebutton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(38, 38, 38)
                                .addComponent(treatmentbutton)
                                .addGap(50, 50, 50))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(welcomearea, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(showpatientbutton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(welcomearea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(treatmentbutton)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showbutton)
                    .addComponent(dischargebutton))
                .addGap(18, 18, 18)
                .addComponent(logoutbutton)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showpatientbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpatientbuttonActionPerformed
        try {
            // TODO add your handling code here:
            DefaultTableModel tablemodel = (DefaultTableModel) table.getModel();
            deleteAllRows(tablemodel);
            Class.forName("com.mysql.jdbc.Driver");
            

            Statement mystmt=null;
            ResultSet myrs;
            int count=0;
            Connection myconn=null;
            String dburl="jdbc:mysql://localhost:3306/Hospital";
            String user="sankalp";
            String pass="qwerty";
            
            myconn=DriverManager.getConnection(dburl,user,pass);
            
            mystmt=myconn.createStatement();
            
            myrs=mystmt.executeQuery("select p_id,p_name,p_disease,dr_id from patient,staff where patient.dr_id=staff.s_id and staff.s_name='"+doctor_name+"';");
            while(myrs.next()){
                int ID=myrs.getInt("p_id");
                String name=myrs.getString("p_name");
                String disease=myrs.getString("p_disease");
                int number = myrs.getInt("dr_id");
                System.out.println(ID +"->" + name +"->" + disease +"->" + number);
                tablemodel.addRow(new Object[]{ID,name,disease,number});
            }
            mystmt.close();
            myconn.close();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(dr_dashboard.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex);
        }

    }//GEN-LAST:event_showpatientbuttonActionPerformed

    private void showbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbuttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tablemodel = (DefaultTableModel) table.getModel();
        int selectedrowindex = table.getSelectedRow();
        String pname= (String) tablemodel.getValueAt(selectedrowindex,1);
        System.out.print(pname);
        close();
        p_dashboard P = new p_dashboard(pname);
        P.setVisible(true);
        
    }//GEN-LAST:event_showbuttonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        // TODO add your handling code here:
        close();
        login P = new login();
        P.setVisible(true);
        
    }//GEN-LAST:event_logoutbuttonActionPerformed

    private void treatmentbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treatmentbuttonActionPerformed
        try {
            // TODO add your handling code here:
            DefaultTableModel tablemodel = (DefaultTableModel) table.getModel();
            int selectedrowindex = table.getSelectedRow();
            String pname= (String) tablemodel.getValueAt(selectedrowindex,1);
            System.out.print(pname);
            close();
            p_treatment P = new p_treatment(pname);
            P.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(dr_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_treatmentbuttonActionPerformed

    private void dischargebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dischargebuttonActionPerformed
        try {
            // TODO add your handling code here:
            DefaultTableModel tablemodel = (DefaultTableModel) table.getModel();
            int selectedrowindex = table.getSelectedRow();
            String pname= (String) tablemodel.getValueAt(selectedrowindex,1);
            Class.forName("com.mysql.jdbc.Driver");

            Statement mystmt=null;
            ResultSet myrs;
            int count=0;
            Connection myconn=null;
            String dburl="jdbc:mysql://localhost:3306/Hospital";
            String user="sankalp";
            String pass="qwerty";
            
            myconn=DriverManager.getConnection(dburl,user,pass);
            
            mystmt=myconn.createStatement();
            
            count=mystmt.executeUpdate("delete from patient where  p_name='"+pname+"';");
            close();
            dr_dashboard D=new dr_dashboard(doctor_name);
            D.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(dr_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
            

    }//GEN-LAST:event_dischargebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dr_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dr_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dr_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dr_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dr_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dischargebutton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton showbutton;
    private javax.swing.JButton showpatientbutton;
    private javax.swing.JTable table;
    private javax.swing.JButton treatmentbutton;
    private javax.swing.JTextField welcomearea;
    // End of variables declaration//GEN-END:variables

    private void close(){
    WindowEvent winClosing=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
}

}
