/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sankalp
 */
public class p_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form p_dashboard
     */
    
    public p_dashboard() {
        initComponents();    }
    String pname;
    public p_dashboard(String Pname) {
        try {
            initComponents();
            this.pname=Pname;
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection myconn=null;
            Statement mystmt=null;
            ResultSet myrs;
            int count=0;
            
            String dburl="jdbc:mysql://localhost:3306/Hospital";
            String user="sankalp";
            String pass="qwerty";
            
            myconn=DriverManager.getConnection(dburl,user,pass);
            
            mystmt=myconn.createStatement();
            System.out.print(  pname );
            myrs=mystmt.executeQuery("select * from patient where p_name='"+pname+"';");
            myrs.next();
            System.out.print(  pname +"->"+ myrs.getString("p_name") + myrs.getString("p_disease"));
            String username1=myrs.getString("p_name");
            int r_id = myrs.getInt("r_id");
            String r_id1 = Integer.toString(r_id);
            int dr_id = myrs.getInt("dr_id");
            
            String disease1=myrs.getString("p_disease");
            String address1=myrs.getString("p_street")+", "+myrs.getString("p_city")+", "+myrs.getString("p_country");
            int age=myrs.getInt("p_age");
            String age1 = Integer.toString(age);
            
            String sex1=myrs.getString("sex");
            username.setText(username1);
            diseasearea.setText(disease1);
            agearea.setText(age1);
            roomarea.setText(r_id1);
            switch (sex1) {
                case "Male":
                    sexarea.setSelectedIndex(0);
                    break;
                case "Female":
                    sexarea.setSelectedIndex(1);
                    break;
                case "Other":
                    sexarea.setSelectedIndex(2);
                    break;
            }
            addressares.setText(address1);
            myrs=mystmt.executeQuery("select patient.m_id from patient where patient.p_name='"+pname+"';");
            myrs.next();
            if(myrs.getString("m_id")==null){
                String medicine1="";
                medicinearea.setText(medicine1);
            }
            else{
                myrs=mystmt.executeQuery("select patient.m_id,m_name from medicine,patient where patient.m_id=medicine.m_id and patient.p_name='"+pname+"';");
                myrs.next();
                String medicine1=myrs.getString("m_name");
                medicinearea.setText(medicine1);
            }
            
            
            
            
            
            long contact;
            String contact1="";
            myrs=mystmt.executeQuery("select patient.p_id,p_number from phone,patient where patient.p_id = phone.p_id and patient.p_name='"+pname+"';");
            myrs.next();
            contact=myrs.getLong("p_number");
            contact1=Long.toString(contact);
            while(myrs.next()){
                contact=myrs.getLong("p_number");
            contact1 = contact1 + ", " + Long.toString(contact);
            
            }
            contactarea.setText(contact1);
            myrs=mystmt.executeQuery("select r_id,r_name,n_name from room,nurse where room.n_id = nurse.n_id and room.r_id='"+r_id+"';");
            myrs.next();
            String n_name = myrs.getString("n_name");
            nursearea.setText(n_name);
            myrs = mystmt.executeQuery("select * from staff where s_id = '"+dr_id+"'");
            myrs.next();
            String sname=myrs.getString("s_name");
            doctorarea.setText(sname);
            mystmt.close();
            myconn.close();
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(p_dashboard.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        addressares = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contactarea = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sexarea = new javax.swing.JComboBox<>();
        diseasearea = new javax.swing.JTextField();
        agearea = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        medicinearea = new javax.swing.JTextField();
        logoutbutton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        roomarea = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        nursearea = new javax.swing.JTextField();
        medicalbutton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        doctorarea = new javax.swing.JTextField();
        accountbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        addressares.setColumns(20);
        addressares.setRows(5);
        jScrollPane1.setViewportView(addressares);

        jLabel2.setText("Name :-");

        jLabel3.setText("Sex :-");

        contactarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactareaActionPerformed(evt);
            }
        });
        contactarea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactareaKeyTyped(evt);
            }
        });

        jLabel7.setText("Disease:-");

        jLabel8.setText("Age:-");

        jLabel4.setText("Address:-");

        sexarea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        diseasearea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diseaseareaActionPerformed(evt);
            }
        });

        agearea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageareaActionPerformed(evt);
            }
        });
        agearea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageareaKeyTyped(evt);
            }
        });

        jLabel5.setText("Contact No.");

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel10.setText("Patient Dashboard");

        jLabel11.setText("Medicine:-");

        medicinearea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineareaActionPerformed(evt);
            }
        });

        logoutbutton.setText("Logout");
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });

        jLabel9.setText("Room ID:-");

        roomarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomareaActionPerformed(evt);
            }
        });
        roomarea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                roomareaKeyTyped(evt);
            }
        });

        jLabel12.setText("Nurse Name:-");

        nursearea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nurseareaActionPerformed(evt);
            }
        });
        nursearea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nurseareaKeyTyped(evt);
            }
        });

        medicalbutton.setText("Go to medical Section");
        medicalbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalbuttonActionPerformed(evt);
            }
        });

        jLabel13.setText("Doctor Name:-");

        doctorarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorareaActionPerformed(evt);
            }
        });
        doctorarea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                doctorareaKeyTyped(evt);
            }
        });

        accountbutton.setText("Go to Accounts Section");
        accountbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(medicinearea, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(contactarea, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(roomarea, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(doctorarea, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel3))
                                    .addGap(47, 47, 47)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sexarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(agearea, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(diseasearea, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(0, 97, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(logoutbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(medicalbutton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nursearea, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(accountbutton)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diseasearea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sexarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(agearea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicinearea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nursearea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutbutton)
                    .addComponent(medicalbutton)
                    .addComponent(accountbutton))
                .addGap(95, 95, 95))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactareaActionPerformed

    private void contactareaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactareaKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_contactareaKeyTyped

    private void diseaseareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diseaseareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diseaseareaActionPerformed

    private void ageareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageareaActionPerformed

    private void ageareaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageareaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ageareaKeyTyped

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void medicineareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineareaActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        // TODO add your handling code here:
            close();
            login D=new login();
            D.setVisible(true);

    }//GEN-LAST:event_logoutbuttonActionPerformed

    private void roomareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomareaActionPerformed

    private void roomareaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roomareaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_roomareaKeyTyped

    private void nurseareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurseareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nurseareaActionPerformed

    private void nurseareaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nurseareaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nurseareaKeyTyped

    private void medicalbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalbuttonActionPerformed
        // TODO add your handling code here:
        close();
        Buy_Tablet B = new Buy_Tablet(pname);
                B.setVisible(true);
    }//GEN-LAST:event_medicalbuttonActionPerformed

    private void doctorareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorareaActionPerformed

    private void doctorareaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doctorareaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorareaKeyTyped

    private void accountbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountbuttonActionPerformed
        try {
            // TODO add your handling code here:
            close();
            p_account P = new p_account(pname);
            P.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(p_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(p_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_accountbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(p_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(p_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(p_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(p_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new p_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountbutton;
    private javax.swing.JTextArea addressares;
    private javax.swing.JTextField agearea;
    private javax.swing.JTextField contactarea;
    private javax.swing.JTextField diseasearea;
    private javax.swing.JTextField doctorarea;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton medicalbutton;
    private javax.swing.JTextField medicinearea;
    private javax.swing.JTextField nursearea;
    private javax.swing.JTextField roomarea;
    private javax.swing.JComboBox<String> sexarea;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

private void close(){
    WindowEvent winClosing=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
}

}
